# main menu navigation url and icon
# 配置菜单导航的名称、路径和图标icon.
menu:
  首页:
    url: /
    icon: fa-home
  博客:
    url: /Home
    icon: fa-home
  前端:
    url: /GuideV2/FrontEndGuide
    icon: fa-archive
  生活:
    url: /garlly
    icon: fa-bicycle
  标签:
    url: /tags
    icon: fa-tags
  分类:
    url: /categories
    icon: fa-bookmark
  归档:
    url: /archives
    icon: fa-archive
  关于:
    url: /about
    icon: fa-user-circle-o  
  大神:
    url: /friends
    icon: fa-address-book

# index page dream text,
# 配置首页显示"梦想"的语句.
dream:
  enable: true
  text: 要用多少个晴天 交换多少张相片 还记得锁在抽屉里面的滴滴点点 小而温馨的空间 因为有你在身边

# Whether to display the title of the recommended posts
# 是否显示推荐文章的标题
recommend:
  showTitle: true

# Configure website favicon and LOGO
# 配置网站favicon和网站LOGO
favicon: /favicon.png
logo: /medias/logo.png

# The configuration of the second button in the home banner,
# including the display name of the button, the font awesome icon, and the hyperlink to the button.
# 首页 banner 中的第二个按钮的配置，包括按钮的显示名称、font awesome图标和按钮的超链接.
indexbtn:
  enable: true
  name: Github
  icon: fa-github-alt
  url: https://github.com/ciweigg2

# Whether to activate the Post TOC, and Configure which title types are supported by TOC support.
# 是否激活文章 TOC 功能，并配置TOC支持选中哪些标题类型.
toc:
  enable: false
  heading: h2, h3, h4

# 是否激活文章末尾的打赏功能，默认激活（你替换为的你自己的微信、支付宝二维码图片、或者使用网络图片也可以）.
reward:
  enable: false
  title: 你的赏识是我前进的动力
  wechat: /medias/reward/wechat.png
  alipay: /medias/reward/alipay.jpg

# Whether to activate the copyright information of the blog and author when copying the post content.
# minCharNumber: Approve copyright information by copying at least how many characters.
# 是否激活复制文章时追加博客和作者的版权信息.
copyright:
  enable: false
  minCharNumber: 120 # 至少复制多少个字符就追加版权信息.
  description: 本文章著作权归作者所有，任何形式的转载都请注明出处。

# Whether to activate the mathjax, this is a global configuration, but the post still does not open the mathjax rendering.
# Considering that the mathjax loading is time consuming,
# you also need to add `mathjax: true` to the Front-matter of the post that needs to be rendered.
# 是否激活mathjax数学公式，这是全局配置，但文章仍然不会都开启mathjax渲染，
# 考虑到mathjax加载比较耗时，你还需要在需要渲染的文章的Front-matter中再加上`mathjax: true`才行.
mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Whether to activate the 'love' effect of clicking on the page.
# 是否激活点击页面的'爱心'效果，默认激活.
clicklove:
  enable: true

# profile in about page, including avatars, career, and personal introductions.
# 在”关于”页面中配置个人信息，包括头像、职业和个人介绍.
profile:
  avatar: /medias/avatar.jpg
  career: Software Engineer
  introduction: If you wish to succeed, you should use persistence as your good friend, experience as your reference, prudence as your brother and hope as your sentry.

# config my projects informations in about page.
# If you don't want to display this `My Projects` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的项目"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myProjects:
  enable: true
  data:
    hexo-theme-matery:
      icon: fa-meetup
      iconBackground: 'linear-gradient(to bottom right, #66BB6A 0%, #81C784 100%)'
      url: http://github.com/blinkfox/hexo-theme-matery
      desc: This is a Hexo blog theme with 'Material Design' and responsive design.
    zealt:
        icon: fa-database
        iconBackground: 'linear-gradient(to bottom right, #F06292 0%, #EF5350 100%)'
        url: https://github.com/blinkfox/zealot
        desc: 一个轻量级的SQL和参数动态生成工具库
    typora-vue-theme:
        icon: fa-file-text-o
        iconBackground: 'linear-gradient(to bottom right, #29B6F6 0%, #1E88E5 100%)'
        url: https://github.com/blinkfox/typora-vue-theme
        desc: This is a typora theme inspired by Vue document style.

# config my skills informations in about page.
# If you don't want to display this `My Skills` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的技能"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
mySkills:
  enable: true
  data:
    Java:
      background: 'linear-gradient(to right, #FF0066 0%, #FF00CC 100%)'
      percent: 85%
    JavaScript:
      background: 'linear-gradient(to right, #9900FF 0%, #CC66FF 100%)'
      percent: 80%
    HTML5:
      background: 'linear-gradient(to right, #2196F3 0%, #42A5F5 100%)'
      percent: 80%
    CSS:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 70%
    SQL:
      background: 'linear-gradient(to right, #4CAF50 0%, #81C784 100%)'
      percent: 90%
    程序设计:
      background: 'linear-gradient(to right, #FFEB3B 0%, #FFF176 100%)'
      percent: 75%

# config gallery of my photos in about page.
# If you don't want to display this `Gallery` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的相册"图片，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myGallery:
  enable: true
  data:
    - /medias/featureimages/0.jpg
    - /medias/featureimages/1.jpg
    - /medias/featureimages/2.jpg

# Whether to display post-calender in the `archive` page
# 设置在归档页面中是否显示'文章日历'控件
postCalendar: true

# the Gitalk config，default disabled
# Gitalk 评论模块的配置，默认为不激活
gitalk:
  enable: true
  owner: ciweigg2
  repo: ciweigg2.github.io
  oauth:
    clientId: 4e9a7bfed30119302290
    clientSecret: 28f6acd9ebbeff567a56b52da427a6622f861607
  admin:
    - ciweigg2

# the Gitment config，default disabled
# Gitment 评论模块的配置，默认为不激活
gitment:
  enable: false
  owner:
  repo:
  oauth:
    clientId:
    clientSecret:

# disqus config, default disabled
# Disqus评论模块的配置，默认为不激活
disqus:
  enable: false
  shortname:

# Livere comment configuration, the default is not activated
# Livere 来必力评论模块的配置，默认为不激活
livere:
  enable: false
  uid:

# The configuration of the Valine comment module is not activated by default.
# To use it, activate the configuration item and set appId and appKey.
# Valine 评论模块的配置，默认为不激活，如要使用，就请激活该配置项，并设置 appId 和 appKey.
valine:
  enable: false
  appId:
  appKey:
  notify: false
  verify: false
  visitor: true
  avatar: 'mm' # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  pageSize: 10
  placeholder: 'just go go' # Comment Box placeholder

# Whether to display fork me on github icon and link, default true, You can change it to your repo address
# 配置是否在 header 中显示 fork me on github 的图标，默认为true，你可以修改为你的仓库地址.
githubLink:
  enable: true
  url: https://github.com/blinkfox/hexo-theme-matery
  title: Fork Me

# The password verification feature of read post. To use this feature,
# activate the configuration item and write the 'password' key and Cipher in the post's Front-matter.
# Note: In order to ensure that the original password will not be leaked to the web page,
# the password of the article must be encrypted by 'SHA256' so that it will not be cracked.
# 阅读文章的密码验证功能，如要使用此功能请激活该配置项，并在对应文章的Front-matter中写上'password'的键和加密后的密文即可.
# 请注意：为了保证密码原文不会被泄露到网页中，文章的密码必须是通过'SHA256'加密的，这样就不会被破解.
verifyPassword:
  enable: false
  promptMessage: 请输入访问本文章的密码
  errorMessage: 密码错误，将返回主页！

# busuanzi(http://busuanzi.ibruce.info/) website statistics
# 不蒜子(http://busuanzi.ibruce.info/) 网站统计
busuanziStatistics:
  enable: true

# Add google analytics configuration
# 添加 Google Analytics 配置
googleAnalytics:
  enable: false
  id:

# The post featured images that needs to be displayed when there is no image.
# 无文章特色图片时需要显示的文章特色图片.
featureImages: 
- http://ciwei2.cn-sh2.ufileos.com/0.jpg
- http://ciwei2.cn-sh2.ufileos.com/1.jpg
- http://ciwei2.cn-sh2.ufileos.com/3.jpg
- http://ciwei2.cn-sh2.ufileos.com/4.jpg
- http://ciwei2.cn-sh2.ufileos.com/5.jpg
- http://ciwei2.cn-sh2.ufileos.com/6.jpg
- http://ciwei2.cn-sh2.ufileos.com/7.jpg
- http://ciwei2.cn-sh2.ufileos.com/8.jpg
- http://ciwei2.cn-sh2.ufileos.com/9.jpg
- http://ciwei2.cn-sh2.ufileos.com/10.jpg
- http://ciwei2.cn-sh2.ufileos.com/11.jpg
- http://ciwei2.cn-sh2.ufileos.com/12.jpg
- http://ciwei2.cn-sh2.ufileos.com/13.jpg
- http://ciwei2.cn-sh2.ufileos.com/14.jpg
- http://ciwei2.cn-sh2.ufileos.com/15.jpg
- http://ciwei2.cn-sh2.ufileos.com/16.jpg
- http://ciwei2.cn-sh2.ufileos.com/17.jpg
- http://ciwei2.cn-sh2.ufileos.com/18.jpg
- http://ciwei2.cn-sh2.ufileos.com/19.jpg
- http://ciwei2.cn-sh2.ufileos.com/20.jpg
- http://ciwei2.cn-sh2.ufileos.com/21.jpg
- http://ciwei2.cn-sh2.ufileos.com/22.jpg
- http://ciwei2.cn-sh2.ufileos.com/23.jpg
- http://ciwei2.cn-sh2.ufileos.com/24.jpg
- http://ciwei2.cn-sh2.ufileos.com/25.jpg
- http://ciwei2.cn-sh2.ufileos.com/26.jpg
- http://ciwei2.cn-sh2.ufileos.com/27.jpg
- http://ciwei2.cn-sh2.ufileos.com/28.jpg
- http://ciwei2.cn-sh2.ufileos.com/29.jpg
- http://ciwei2.cn-sh2.ufileos.com/30.jpg
- http://ciwei2.cn-sh2.ufileos.com/31.jpg
- http://ciwei2.cn-sh2.ufileos.com/32.jpg
- http://ciwei2.cn-sh2.ufileos.com/33.jpg
- http://ciwei2.cn-sh2.ufileos.com/34.jpg
- http://ciwei2.cn-sh2.ufileos.com/35.jpg
- http://ciwei2.cn-sh2.ufileos.com/36.jpg
- http://ciwei2.cn-sh2.ufileos.com/37.jpg
- http://ciwei2.cn-sh2.ufileos.com/38.jpg
- http://ciwei2.cn-sh2.ufileos.com/39.jpg
- http://ciwei2.cn-sh2.ufileos.com/40.jpg
- http://ciwei2.cn-sh2.ufileos.com/41.jpg
- http://ciwei2.cn-sh2.ufileos.com/42.jpg
- http://ciwei2.cn-sh2.ufileos.com/45.jpg
- http://ciwei2.cn-sh2.ufileos.com/46.jpg
- http://ciwei2.cn-sh2.ufileos.com/47.jpg
- http://ciwei2.cn-sh2.ufileos.com/48.jpg
- http://ciwei2.cn-sh2.ufileos.com/49.jpg
- http://ciwei2.cn-sh2.ufileos.com/50.jpg
- http://ciwei2.cn-sh2.ufileos.com/51.jpg
- http://ciwei2.cn-sh2.ufileos.com/52.jpg
- http://ciwei2.cn-sh2.ufileos.com/53.jpg
- http://ciwei2.cn-sh2.ufileos.com/54.jpg
- http://ciwei2.cn-sh2.ufileos.com/55.jpg
- http://ciwei2.cn-sh2.ufileos.com/56.jpg
- http://ciwei2.cn-sh2.ufileos.com/57.jpg
- http://ciwei2.cn-sh2.ufileos.com/58.jpg
- http://ciwei2.cn-sh2.ufileos.com/59.jpg
- http://ciwei2.cn-sh2.ufileos.com/60.jpg
- http://ciwei2.cn-sh2.ufileos.com/61.jpg
- http://ciwei2.cn-sh2.ufileos.com/62.jpg
- http://ciwei2.cn-sh2.ufileos.com/63.jpg
- http://ciwei2.cn-sh2.ufileos.com/64.jpg
- http://ciwei2.cn-sh2.ufileos.com/65.jpg
- http://ciwei2.cn-sh2.ufileos.com/66.jpg
- http://ciwei2.cn-sh2.ufileos.com/67.jpg
- http://ciwei2.cn-sh2.ufileos.com/68.jpg
- http://ciwei2.cn-sh2.ufileos.com/69.jpg
- http://ciwei2.cn-sh2.ufileos.com/70.jpg
- http://ciwei2.cn-sh2.ufileos.com/71.jpg
- http://ciwei2.cn-sh2.ufileos.com/72.jpg
- http://ciwei2.cn-sh2.ufileos.com/73.jpg
- http://ciwei2.cn-sh2.ufileos.com/74.jpg
- http://ciwei2.cn-sh2.ufileos.com/75.jpg
- http://ciwei2.cn-sh2.ufileos.com/76.jpg
- http://ciwei2.cn-sh2.ufileos.com/77.jpg
- http://ciwei2.cn-sh2.ufileos.com/78.jpg
- http://ciwei2.cn-sh2.ufileos.com/79.jpg
- http://ciwei2.cn-sh2.ufileos.com/80.jpg
- http://ciwei2.cn-sh2.ufileos.com/81.jpg
- http://ciwei2.cn-sh2.ufileos.com/82.jpg
- http://ciwei2.cn-sh2.ufileos.com/83.jpg
- http://ciwei2.cn-sh2.ufileos.com/84.jpg
- http://ciwei2.cn-sh2.ufileos.com/85.jpg
- http://ciwei2.cn-sh2.ufileos.com/86.jpg
- http://ciwei2.cn-sh2.ufileos.com/87.jpg
- http://ciwei2.cn-sh2.ufileos.com/88.jpg
- http://ciwei2.cn-sh2.ufileos.com/89.jpg
- http://ciwei2.cn-sh2.ufileos.com/90.jpg
- http://ciwei2.cn-sh2.ufileos.com/91.jpg
- http://ciwei2.cn-sh2.ufileos.com/92.jpg
- http://ciwei2.cn-sh2.ufileos.com/93.jpg
- http://ciwei2.cn-sh2.ufileos.com/94.jpg
- http://ciwei2.cn-sh2.ufileos.com/95.jpg
- http://ciwei2.cn-sh2.ufileos.com/96.jpg
- http://ciwei2.cn-sh2.ufileos.com/97.jpg
- http://ciwei2.cn-sh2.ufileos.com/98.jpg
- http://ciwei2.cn-sh2.ufileos.com/99.jpg
- http://ciwei2.cn-sh2.ufileos.com/100.jpg
- http://ciwei2.cn-sh2.ufileos.com/101.jpg
- http://ciwei2.cn-sh2.ufileos.com/102.jpg
- http://ciwei2.cn-sh2.ufileos.com/103.jpg
- http://ciwei2.cn-sh2.ufileos.com/104.jpg
- http://ciwei2.cn-sh2.ufileos.com/105.jpg
- http://ciwei2.cn-sh2.ufileos.com/106.jpg
- http://ciwei2.cn-sh2.ufileos.com/107.jpg
- http://ciwei2.cn-sh2.ufileos.com/108.jpg
- http://ciwei2.cn-sh2.ufileos.com/109.jpg
- http://ciwei2.cn-sh2.ufileos.com/110.jpg
- http://ciwei2.cn-sh2.ufileos.com/111.jpg
- http://ciwei2.cn-sh2.ufileos.com/112.jpg
- http://ciwei2.cn-sh2.ufileos.com/113.jpg
- http://ciwei2.cn-sh2.ufileos.com/114.jpg
- http://ciwei2.cn-sh2.ufileos.com/115.jpg
- http://ciwei2.cn-sh2.ufileos.com/116.jpg
- http://ciwei2.cn-sh2.ufileos.com/117.jpg
- http://ciwei2.cn-sh2.ufileos.com/118.jpg
- http://ciwei2.cn-sh2.ufileos.com/119.jpg
- http://ciwei2.cn-sh2.ufileos.com/120.jpg
- http://ciwei2.cn-sh2.ufileos.com/121.jpg
- http://ciwei2.cn-sh2.ufileos.com/122.jpg
- http://ciwei2.cn-sh2.ufileos.com/123.jpg
- http://ciwei2.cn-sh2.ufileos.com/124.jpg
- http://ciwei2.cn-sh2.ufileos.com/125.jpg
